# left image LDC LUT definition
left_lut_file_path:                 $(find zed_capture)/config/SN5867575_HD_LUT_left.bin

# right image LDC LUT definition
right_lut_file_path:                $(find zed_capture)/config/SN5867575_HD_LUT_right.bin

# input_format
# should be 1: YUV422
input_format:                       1

# SDE type
# 0: Single-layer SDE, 1: Multi-layer SDE
sde_algo_type:                      0

# For multi-layer SDE only
# number of layers (2, 3)
num_layers:                         2


####### SDE params BEGIN #######

# minimum disparity in pixels
# minimum disparity (0 -> 0 pixels, 1 -> -3 pixels)
disparity_min:                      0

# <disparity in pixels>, maximum disparity in pixels
# maximum disparity (0 -> 63 pixels, 1 -> 127 pixels)
disparity_max:                      1

# <0 - 255>, left-right consistency check threshold in pixels
threshold_left_right:               3

# <0 or 1>, disable/enable texture based filtering
texture_filter_enable:              0

# <0 - 255>, scaled threshold for texture based filtering
threshold_texture:                  0

# <0 - 127>, Optimization penalty constant for small disparity change
aggregation_penalty_p1:             32

# <0 - 255>, Optimization penalty constant for large disparity change
aggregation_penalty_p2:             192

# <0, 1>, median filter in SDE
median_filter_enable:               1

####### SDE params END #######

# baseline in meter
stereo_baseline:                    0.12 

# Enable PC generation
enable_pc:                          0

# PC subsampling ratio (1, 2, 4)
pc_subsample_ratio:                 1

# Enabling flag for the following point cloud configurations:
# sde_confidence_threshold, 
# point_low_x, point_high_x, point_low_y, point_high_y, point_low_z, point_high_z
use_pc_config:                      1

# disparity threshold to be mapped to point cloud (0 ~ 7)
sde_confidence_threshold:           1

# 3D point range to be rendered -
#   Only 3D points in [low_x:high_x, low_y:high_y, low_z:high_z] 
#   are redered
#
#       (Z)   (Y)
#        |   / 
#        |  /
#        | /
#        |/________ (X)
#

# Low X limit in meter
point_low_x:                       -10.0 

# Hig X limit in meter  
point_high_x:                       10.0 

# Low Y limits in meter (depth)
point_low_y:                        0.0

# High Y limits in meter (depth)
point_high_y:                       10.0

# Low Z limit in meter (depth)
point_low_z:                       -2.0

# High Z limit in meter (depth)
point_high_z:                       5.0

# interactive mode
#  0 - disable
#  1 - enable
is_interactive:                     0

# Flag to indicate if the graph should be exported
#  0 - disable
#  1 - enable
exportGraph:                        0

# Flag to indicate if the performance data should be exported
# to a file
#  0 - disable
#  1 - enable
exportPerfStats:                    0

# Real-time logging enable.
#  0 - disable
#  1 - enable
rtLogEnable:                        0

# <1 - 8>, pipeline depth
pipeline_depth:                     4

# Core deployment
# merge node in multi-layer SDE
# TIVX_TARGET_DSP1
# TIVX_TARGET_DSP2
# TIVX_TARGET_A72_0
# TIVX_TARGET_A72_1
disp_merge_deploy_core:             TIVX_TARGET_A72_0

# holing filling node in multi-layer SDE
# TIVX_TARGET_DSP1
# TIVX_TARGET_DSP2
# TIVX_TARGET_A72_0
# TIVX_TARGET_A72_1
hole_filling_deploy_core:           TIVX_TARGET_A72_0

# point cloud creation node in detection
# TIVX_TARGET_DSP1
# TIVX_TARGET_DSP2
color_conv_deploy_core:             TIVX_TARGET_DSP1

# OG map creation node in detection
# TIVX_TARGET_DSP1
# TIVX_TARGET_DSP2
# TIVX_TARGET_A72_0
# TIVX_TARGET_A72_1
triang_deploy_core:                 TIVX_TARGET_A72_0



