# Maximum number of Semantic Segmentation classes
num_classes:            20

# interactive mode
is_interactive:         0

# to enable showing output on display when display_option = 1
display_option:         1

# pipeline depth
pipeline_depth:         4

# flag to indicate if the graph should be exported
#  0 - disable
#  1 - enable
exportGraph:            0

# real-time logging enable.
#  0 - disable
#  1 - enable
rtLogEnable:            0

# log level for the app
# 0 - DEBUG: Used to show general debug messages
# 1 - INFO: Used to show run-time processing debug
# 2 - WARN: Used to warning developers of possible issues
# 3 - ERROR: Used for most errors
log_level:              2
